"""
Analysis & Copilot Schemas.
Defines structured formats for procurement analysis results, scoring, and copilot responses.
"""

from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


# ── Job Status ──────────────────────────────────────────────────────────────────

class JobStatus(str, Enum):
    UPLOADED = "UPLOADED"
    EXTRACTING = "EXTRACTING"
    VALIDATING = "VALIDATING"
    ANALYZING = "ANALYZING"
    GENERATING_RECOMMENDATION = "GENERATING_RECOMMENDATION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class JobResponse(BaseModel):
    job_id: str
    status: JobStatus
    progress_message: str = ""
    result: Optional[dict] = None


# ── Scoring ─────────────────────────────────────────────────────────────────────

class ScoringWeights(BaseModel):
    """User-configurable scoring weights. Must sum to 1.0."""
    cost_weight: float = Field(0.4, ge=0, le=1)
    warranty_weight: float = Field(0.3, ge=0, le=1)
    delivery_weight: float = Field(0.3, ge=0, le=1)


class VendorScore(BaseModel):
    """Deterministic score for a single vendor."""
    vendor_name: str
    cost_score: float = Field(..., ge=0, le=100)
    warranty_score: float = Field(..., ge=0, le=100)
    delivery_score: float = Field(..., ge=0, le=100)
    overall_score: float = Field(..., ge=0, le=100)
    rank: int = Field(..., ge=1)


# ── Risk Flags ──────────────────────────────────────────────────────────────────

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskFlag(BaseModel):
    """A single procurement risk detected by the analysis engine."""
    vendor_name: str
    risk_type: str  # e.g., "SHORT_WARRANTY", "LONG_DELIVERY", "MISSING_FIELD"
    description: str
    level: RiskLevel


# ── Analysis Results ────────────────────────────────────────────────────────────

class SavingsOpportunity(BaseModel):
    """Cost comparison between two vendors."""
    cheaper_vendor: str
    expensive_vendor: str
    savings_amount: float
    savings_percentage: float


class ProcurementAnalysis(BaseModel):
    """
    The complete Procurement Intelligence Package.
    Generated by the deterministic analysis engine — NO LLM involved.
    """
    vendor_scores: list[VendorScore]
    recommended_vendor: str
    recommendation_reason: str  # Short deterministic reason
    risk_flags: list[RiskFlag]
    savings_opportunities: list[SavingsOpportunity]
    cost_comparison: dict  # vendor_name -> grand_total
    warranty_comparison: dict  # vendor_name -> warranty_months
    delivery_comparison: dict  # vendor_name -> delivery_days


# ── Copilot ─────────────────────────────────────────────────────────────────────

class CopilotRequest(BaseModel):
    """User's question to the procurement copilot."""
    job_id: str
    message: str
    analysis_context: Optional[ProcurementAnalysis] = None


class NegotiateRequest(BaseModel):
    """Request to generate a negotiation strategy."""
    job_id: str
    vendor_name: str
    analysis_context: Optional[ProcurementAnalysis] = None


class CopilotResponse(BaseModel):
    """Copilot's grounded response."""
    response: str
    sources: list[str] = []  # What data the response is grounded in
